version: '3'

services:
    server:
        build:
            context: '../server'
        container_name: tic-server
        restart: 'always'
        ports:
            - '5000:5000'
    client:
        build:
            context: '../client'
        container_name: tic-client
        depends_on:
            - server
        restart: 'always'
        ports:
            - '3000:80'
